
const { isPalindrome } = require('../../src/isPalindrome'); // Assuming your module is in a file named 'isPalindrome.js'
const { generateNumber } = require('./numberGenerator'); // Assuming your number generator module is in a file named 'numberGenerator.js'

describe('Integration test for isPalindrome function', () => {
    it('should correctly identify palindromes generated by number generator', () => {
        // Generate a palindrome number using a number generator function
        const palindromeNumber = generateNumber();

        // Check if the generated number is a palindrome using isPalindrome function
        const isPalindromeResult = isPalindrome(palindromeNumber);
        
        // Expect the result to be true
        expect(isPalindromeResult).to.be.true;
    });
});
