name: Python Application CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Unit Tests
      run: |
        cd tests
        python -m unittest discover

  deploy-to-dev:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Development Environment
      run: |
        echo "Deploying to development environment"
        # Add your deployment commands here. This can vary greatly depending on your environment.
        # For example, you might use SSH, SCP, Kubernetes, Docker, AWS CLI, Azure CLI, etc.
